version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bjarne-studylife_server_1
      APP_PORT: 8080

  server:
    image: ghcr.io/lukislp/studylife-server:latest
    restart: unless-stopped
    volumes:
      - studylife-data:/app/app_data
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      Worker__Enabled: "true"
    user: "1000:1000"
    init: true

volumes:
  studylife-data: