version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: umbrel-heliumedu_frontend_1
      APP_PORT: 8080

  db:
    image: mysql:8.4

    environment:
      MYSQL_ROOT_PASSWORD: helium-root
      MYSQL_DATABASE: platform_dev-local
      MYSQL_USER: helium
      MYSQL_PASSWORD: helium

    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      timeout: 3s
      retries: 20
      interval: 5s

    volumes:
      - ${APP_DATA_DIR}/data/mysql:/var/lib/mysql

    restart: on-failure

  cache:
    image: valkey/valkey:8.1

    volumes:
      - ${APP_DATA_DIR}/data/valkey:/data

    restart: on-failure

  storage:
    image: localstack/localstack:4.13.1

    environment:
      ENVIRONMENT: dev-local

    volumes:
      - ${APP_DATA_DIR}/data/localstack:/var/lib/localstack
      - ./container/init-localstack.py:/etc/localstack/init/ready.d/init-localstack.py

    restart: on-failure

  resource:
    image: helium/platform-resource:arm64-latest

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      storage:
        condition: service_started

    restart: "no"

  api:
    image: helium/platform-api:arm64-latest

    env_file:
      - .env

    expose:
      - "8000"

    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      storage:
        condition: service_started
      resource:
        condition: service_completed_successfully

    restart: on-failure

  worker:
    image: helium/platform-worker:arm64-latest

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      storage:
        condition: service_started
      resource:
        condition: service_completed_successfully

    restart: on-failure

  frontend:
    image: YOUR_DOCKERHUB_USERNAME/helium-frontend:2.5.7

    expose:
      - "8080"

    depends_on:
      api:
        condition: service_started

    restart: on-failure